# Generated by Django 5.1.3 on 2024-12-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='catergory',
            field=models.CharField(choices=[('Sold', 'Sold'), ('New', 'New'), ('Discount', 'Discount')], default='New', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
