# Generated by Django 5.1.3 on 2024-12-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_product_category_product_catergory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catergory',
            new_name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Hair', 'Sold'), ('Perfume', 'Perfume'), ('Shoe', 'Shoe'), ('Cloth', 'Cloth'), ('Bag', 'Bag'), ('Others', 'Others')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
