# Generated by Django 5.1.3 on 2025-01-12 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_product_image_product_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='variant',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='customer.productcolor'),
        ),
    ]
