# Generated by Django 5.1.3 on 2025-01-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_productcolor_variant_productvariant_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.ManyToManyField(to='customer.productcolor'),
        ),
    ]
