# Generated by Django 5.1.3 on 2025-01-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_productcolor_color_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qualities',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customer',
        ),
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ManyToManyField(to='customer.customer'),
        ),
    ]
