# Generated by Django 5.1.3 on 2025-01-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_order_phone_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='productimage',
            name='type',
            field=models.CharField(choices=[('Main', 'Main'), ('Other', 'Other')], default='Main', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='customer',
            field=models.ManyToManyField(null=True, to='customer.customer'),
        ),
    ]
