# Generated by Django 5.1.3 on 2025-01-13 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_notice_slide_productimage_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='description',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='SlideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.slide')),
            ],
        ),
    ]
