# Generated by Django 5.1.3 on 2025-01-13 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_slide_description_slide_title_slideimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlideImage',
        ),
    ]
