# Generated by Django 5.1.3 on 2025-01-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_slide_description_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='customer',
            field=models.ManyToManyField(to='customer.customer'),
        ),
    ]
