# Generated by Django 5.1.3 on 2025-01-18 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_customer_username_alter_product_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='customer.activities'),
        ),
    ]
