# Generated by Django 5.1.3 on 2025-01-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_customer_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='activity',
        ),
    ]
