# Generated by Django 5.1.3 on 2025-05-26 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_reply_customer_reply_replying_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='thumb_down',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='thumb_up',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='thumb_down',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='thumb_up',
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='profilepic.png', null=True, upload_to='profile/'),
        ),
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_up', models.BooleanField(default=False)),
                ('thumb_down', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='customer.comment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to='customer.customer')),
            ],
            options={
                'unique_together': {('comment', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='ReplyVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_up', models.BooleanField(default=False)),
                ('thumb_down', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_votes', to='customer.customer')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='customer.reply')),
            ],
            options={
                'unique_together': {('reply', 'customer')},
            },
        ),
    ]
