# Generated by Django 5.1.3 on 2025-05-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_remove_comment_thumb_down_remove_comment_thumb_up_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.DeleteModel(
            name='ReplyVote',
        ),
    ]
