# Generated by Django 5.1.3 on 2025-06-25 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_passwordresetcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='color',
            new_name='colors',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='customer.product'),
        ),
    ]
