# Generated by Django 5.1.3 on 2025-06-25 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_rename_color_productvariant_colors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='color_name',
        ),
        migrations.AddField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='customer.product'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='colors',
            field=models.ManyToManyField(to='customer.color'),
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('colors', models.ManyToManyField(to='customer.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_variants', to='customer.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
