# Generated by Django 5.1.3 on 2025-06-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_color_remove_productcolor_color_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='product',
            name='limit',
            field=models.IntegerField(null=True),
        ),
    ]
