# Generated by Django 5.1.3 on 2025-06-27 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_order_product_color_order_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_color',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_size',
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.ManyToManyField(to='customer.color')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='customer.order')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.productsize')),
            ],
        ),
    ]
