# Generated by Django 5.1.3 on 2025-06-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_remove_order_product_color_remove_order_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Ongoing', 'Ongoing'), ('Inactive', 'Inactive')], default='Inactive', max_length=20),
        ),
    ]
