# Generated by Django 5.1.3 on 2025-06-28 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailColorQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.color')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.orderdetail')),
            ],
            options={
                'verbose_name': 'Order Detail Color Quantity',
                'verbose_name_plural': 'Order Detail Color Quantities',
                'unique_together': {('order_detail', 'color')},
            },
        ),
    ]
