# Generated by Django 5.1.3 on 2025-06-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_orderdetailcolorquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorder',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
