# Generated by Django 5.1.3 on 2025-06-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_shippingorder_gmail_shippingorder_whatsapp_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingorder',
            old_name='gmail',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='shippingorder',
            name='order',
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='orders',
            field=models.ManyToManyField(to='customer.order'),
        ),
    ]
