# Generated by Django 5.1.3 on 2025-06-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_rename_gmail_shippingorder_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorder',
            name='order_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
