# Generated by Django 5.1.3 on 2025-07-07 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_shippingorder_order_note_shippingorder_payment_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='activities',
            name='like',
        ),
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.CharField(max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.guestcustomer'),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='guest_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.guestcustomer'),
        ),
    ]
