# Generated by Django 5.1.3 on 2025-07-07 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0033_alter_order_customer_alter_shippingorder_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='product',
        ),
        migrations.AddField(
            model_name='activities',
            name='guest_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.guestcustomer'),
        ),
    ]
