# Generated by Django 5.1.3 on 2025-07-07 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0034_remove_activities_product_activities_guest_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.product'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
