# Generated by Django 5.1.3 on 2025-07-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0035_activities_product_alter_activities_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='guest_customer',
        ),
        migrations.AddField(
            model_name='activities',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activities',
            name='selected_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='selected_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='cart',
            field=models.BooleanField(default=False),
        ),
    ]
