# Generated by Django 5.1.3 on 2025-07-08 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0036_remove_activities_guest_customer_activities_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='guest_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.guestcustomer'),
        ),
    ]
