# Generated by Django 5.1.3 on 2025-07-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0037_activities_guest_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestcustomer',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guestcustomer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guestcustomer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guestcustomer',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
