# Generated by Django 5.1.3 on 2025-07-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0038_alter_guestcustomer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
