# Generated by Django 5.1.3 on 2025-07-09 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0039_activities_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='replying_to',
            new_name='replying_customer',
        ),
        migrations.AddField(
            model_name='comment',
            name='guest_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.guestcustomer'),
        ),
        migrations.AddField(
            model_name='reply',
            name='guest_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.guestcustomer'),
        ),
        migrations.AddField(
            model_name='reply',
            name='replying_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_to', to='customer.guestcustomer'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.DeleteModel(
            name='CommentVote',
        ),
    ]
