# Generated by Django 5.1.3 on 2025-07-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0040_rename_replying_to_reply_replying_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorder',
            name='mode',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Pickup', 'Pickup')], default='Delivery', max_length=10),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='save',
            field=models.CharField(choices=[('Save', 'Save'), ('Unsave', 'Unsave')], default='Unsave', max_length=10),
        ),
    ]
