# Generated by Django 5.1.3 on 2025-07-12 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0041_shippingorder_mode_shippingorder_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingorder',
            old_name='save',
            new_name='save_status',
        ),
    ]
