# Generated by Django 5.1.3 on 2025-07-12 04:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0042_rename_save_shippingorder_save_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
