# Generated by Django 5.1.3 on 2025-07-13 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0043_shippingorder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorder',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='final_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_percent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('one_time_use', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('used_by_customer', models.ManyToManyField(blank=True, to='customer.customer')),
                ('used_by_guest', models.ManyToManyField(blank=True, to='customer.guestcustomer')),
            ],
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.coupon'),
        ),
    ]
