# Generated by Django 5.1.3 on 2025-07-13 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0044_shippingorder_coupon_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingorder',
            name='coupon_discount',
        ),
        migrations.RemoveField(
            model_name='shippingorder',
            name='final_total',
        ),
    ]
