# Generated by Django 5.1.3 on 2025-07-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0045_remove_shippingorder_coupon_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='one_time_use',
            field=models.BooleanField(default=True),
        ),
    ]
