# Generated by Django 5.1.3 on 2025-07-15 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0046_remove_coupon_created_at_alter_coupon_one_time_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='broadcast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='notice',
            name='guest_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.guestcustomer'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='one_time_use',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='OrderDetailColorQuantity',
        ),
    ]
