# Generated by Django 5.1.3 on 2025-07-15 05:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0047_notice_broadcast_notice_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Sold', 'Sold'), ('New', 'New'), ('Discount', 'Discount')], default='New', max_length=20),
        ),
    ]
