# Generated by Django 5.1.3 on 2025-07-16 02:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0048_product_created_at_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notice',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
