# Generated by Django 5.1.3 on 2025-07-17 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0050_alter_notice_created_at_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='from_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notices', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='notice',
            name='from_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_guest_notices', to='customer.guestcustomer'),
        ),
    ]
