# Generated by Django 5.1.3 on 2025-07-17 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0051_notice_from_customer_notice_from_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='from_guest',
        ),
        migrations.AddField(
            model_name='notice',
            name='from_guest_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notices', to='customer.guestcustomer'),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notices', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='guest_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notices', to='customer.guestcustomer'),
        ),
    ]
