# Generated by Django 5.1.3 on 2025-07-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0052_remove_notice_from_guest_notice_from_guest_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
