# Generated by Django 5.1.3 on 2025-07-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0053_notice_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
