# Generated by Django 5.1.3 on 2025-07-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0054_alter_notice_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Ongoing', 'Ongoing'), ('Inactive', 'Inactive'), ('Approved', 'Approved')], default='Inactive', max_length=20),
        ),
    ]
