# Generated by Django 5.1.3 on 2025-07-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0057_alter_customer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
