# Generated by Django 5.1.3 on 2025-07-20 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0059_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
