# Generated by Django 5.1.3 on 2025-07-20 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0060_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer',
        ),
    ]
