# Generated by Django 5.1.3 on 2025-07-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0061_remove_product_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
