# Generated by Django 5.1.3 on 2025-07-31 17:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0062_alter_product_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slides/'),
        ),
    ]
