# Generated by Django 5.1.3 on 2025-08-02 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0063_slide_created_at_alter_slide_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='slide',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
