# Generated by Django 5.1.3 on 2025-08-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0065_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingorder',
            name='payment_proof',
        ),
    ]
