# Generated by Django 5.1.3 on 2025-08-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0066_remove_shippingorder_payment_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Ongoing', 'Ongoing'), ('Inactive', 'Inactive')], default='Inactive', max_length=20),
        ),
    ]
