# Generated by Django 5.1.3 on 2025-08-14 20:54

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0070_alter_customer_image_alter_slide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='default/profilepic.png', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='profile/'),
        ),
    ]
