# Generated by Django 5.1.3 on 2025-08-15 10:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0074_alter_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_image', max_length=255, null=True, verbose_name='image'),
        ),
    ]
