from django.urls import path
from . import views
from django.contrib.auth import views as auth_view

urlpatterns = [
    path('', views.landingpage, name='landingpage'),
    path('verify-code/<int:pk>/', views.verify_code, name='verify_code'),
    path('reset-password/<int:pk>/<str:code>/', views.reset_password, name='reset'),
    path('home/', views.home, name='home'),
    path('customer/', views.customer, name='customer'),
   path('api/customers/', views.get_customer_data_json, name='api_customers'),
   path('ajax/get-coupons/', views.get_all_coupons, name='get_all_coupons'),
    path('ajax/delete-coupon/<int:coupon_id>/', views.delete_coupon, name='delete_coupon'),
    path('ajax/create-coupon/', views.create_coupon_ajax, name='create_coupon_ajax'),
    path('ajax/send-coupon-email/', views.send_coupon_email, name='send_coupon_email'),
    path('customer/<str:type>/<int:id>/', views.customer_detail_view, name='customer_detail'),
    path('ajax/create-comment/', views.create_comment_ajax, name='ajax_create_comment'),
    path('delete-comment/', views.delete_comment, name='delete_comment'),
    path('ajax/create-reply/', views.ajax_create_reply, name='ajax_create_reply'),
    path('delete-reply/', views.delete_reply, name='delete_reply'),
    path('notifications/delete/<int:notice_id>/', views.delete_notification_view, name='delete-notification'),
    path('prepare-payment/', views.prepare_payment, name='prepare_payment'),
     path('shipping/save/', views.collect_shipping_info, name='collect_shipping_info'),
    path('create_slides/', views.test, name='test'),
    path('add_product/', views.add_product, name='add_product'),
    path('test/', views.tests, name='tests'),
    path('notifications/', views.notification_list_view, name='notification-list'),
    path('notifications/create/', views.create_notification_view, name='create-notification'),
    path('slides/delete/<int:slide_id>/', views.delete_slide, name='delete_slide'),
    path('product/<int:pk>/delete/', views.delete_product, name='delete_product'),
    path('remove-from-cart/<int:activity_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('apply-coupon/', views.apply_coupon, name='apply_coupon'),
    path('remove-coupon/', views.remove_coupon, name='remove_coupon'),
    path('mark-notice-read/<int:notice_id>/', views.mark_notice_read, name='mark_notice_read'),
    path('shop/', views.shop, name='shop'),
    path('admin_order/', views.orders, name='admin_order'),
    path("update-order-status/<int:shipping_id>/", views.update_order_status, name="update_order_status"),
    path('edit_order/<int:shipping_id>/', views.edit_order, name='edit_order'),
    path('admin_notice/', views.admin_notice, name='admin_notice'),
    path('notification/', views.notification, name='notification'), 
    path('error/', views.error, name='error'),
    path('email', views.create_order_email, name='email'),
    path('payment/success/', views.payment_success, name='payment_success'),


    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logoutpage, name='logout'),
    path('mark-notice-read/', views.mark_notice_as_read, name='mark_notice_read'),
    path('product/<int:pk>/', views.product, name='product'),
    path('edit/product/<int:pk>/', views.edit_product, name='edit_product'),
    path('custom-send/', views.custom_send_email, name='custom_send_email'),
    path('resend-otp/<int:pk>/', views.resend_otp_email, name='resend_otp'),
    path('order_confirm/', views.order_confirm, name='order_confirm'),
    path('category/<str:category_name>/', views.category_view, name='category'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('shop/product/', views.products, name='admin-products'),
    path('verify-password/', views.verify_current_password, name='verify_current_password'),
    path('change-password/', views.change_password, name='change_password'),
    path('carts/', views.view_cart, name='view_cart'),
    path('prepare-payment-ajax/', views.prepare_payment_ajax, name='prepare_payment_ajax'),
    
    path('cart/add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
     path('shipping/validate/', views.validate_shipping_order, name='validate_shipping_order'),
    path('checkout/', views.checkout, name='checkout'),
    #path('shipping/', views.shipping_order, name='shipping_order'),
     path('update-shipping-address/<int:id>/', views.update_shipping_address, name='update_shipping_address'),
    path('unsave-shipping-address/<int:id>/', views.unsave_shipping_address, name='unsave_shipping_address'),
    path('orders/track/', views.track_order, name='track_order'),
    path('orders/detail/<int:shipping_id>/', views.order_detail, name='order_detail'),

    path("reset_password/", auth_view.PasswordResetView.as_view(), name="reset_password"), 
    path("reset_password_sent/", auth_view.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_view.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset_password_complete/", auth_view.PasswordResetCompleteView.as_view(), name="password_reset_complete"),

]

